# MINED PRIMITIVE (Focus 1 co-occurrence pipeline)
# pid: python-datascience::pdg336::sqlalchemy.Column+sqlalchemy.Integer+sqlalchemy.PrimaryKeyConstraint
# name: sqlalchemy_primitive
# summary: Uses sqlalchemy.Column, sqlalchemy.Integer, sqlalchemy.PrimaryKeyConstraint, sqlalchemy.String across 2 repos
# anchor_symbols: ['sqlalchemy.Column', 'sqlalchemy.Integer', 'sqlalchemy.PrimaryKeyConstraint', 'sqlalchemy.String', 'sqlalchemy.Text']
# observed in 2 repos: ['AgnostiqHQ__covalent', 'airbnb__knowledge-repo']...

# --- from airbnb__knowledge-repo::knowledge_repo/app/migrations/versions/d15f6cac07e1_add_subtitle_field_to_post_database.py::upgrade ---
def upgrade():
    op.add_column('posts', sa.Column('subtitle', sa.Text(), nullable=True))

# --- from airbnb__knowledge-repo::knowledge_repo/app/migrations/versions/9715822acf6c_add_errorlog_table.py::downgrade ---
def downgrade():
    with op.batch_alter_table('pageviews') as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.drop_column('id_errorlog')

    op.drop_table('errorlog')

# --- from AgnostiqHQ__covalent::covalent_migrations/versions/97202f5f47cb_v13.py::upgrade ---
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("electrons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_filename", sa.Text(), nullable=True))
        batch_op.drop_column("info_filename")

    # ### end Alembic commands ###

# --- from AgnostiqHQ__covalent::covalent_migrations/versions/f64ecaa040d5_add_jobs_db_table.py::upgrade ---
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("cancel_successful", sa.Boolean(), nullable=False),
        sa.Column("job_handle", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("electron_dependency", schema=None) as batch_op:
        batch_op.create_foreign_key("electron_link", "electrons", ["parent_electron_id"], ["id"])

    with op.batch_alter_table("electrons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("job_id_link", "jobs", ["job_id"], ["id"])

    # ### end Alembic commands ###
