# MINED PRIMITIVE (Focus 1 co-occurrence pipeline)
# pid: python-datascience::pdg890::sqlalchemy.Column+sqlalchemy.ForeignKey+sqlalchemy.String
# name: sqlalchemy_primitive
# summary: Uses sqlalchemy.Column, sqlalchemy.ForeignKey, sqlalchemy.String across 2 repos
# anchor_symbols: ['sqlalchemy.Column', 'sqlalchemy.ForeignKey', 'sqlalchemy.String']
# observed in 2 repos: ['insitro__redun', 'ottogroup__palladium']...

# --- from ottogroup__palladium::palladium/persistence.py::Database.PropertyClass ---
def PropertyClass(self, Base):
        class Property(Base):
            __tablename__ = self._table_postfix('properties')
            id = Column(Integer, primary_key=True)
            name = Column(String(length=10 ** 3))
            value = Column(String(length=10 ** 3), nullable=False)
        return Property

# --- from ottogroup__palladium::palladium/persistence.py::Database.DBModelChunkClass ---
def DBModelChunkClass(self, Base):
        class DBModelChunk(Base):
            __tablename__ = self._table_postfix('model_chunks')
            id = Column(Integer, primary_key=True)
            model_version = Column(
                ForeignKey('{}.version'.format(self._table_postfix('models'))))
            blob = Column(LargeBinary, nullable=False)
        return DBModelChunk

# --- from insitro__redun::redun/backends/db/alembic/versions/d4af139b6f53_add_job_execution_id.py::upgrade ---
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.add_column(sa.Column("execution_id", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_job_execution_id"), ["execution_id"], unique=False)
        batch_op.create_foreign_key(
            "ct_job_execution_id",
            "execution",
            ["execution_id"],
            ["id"],
            deferrable=True,
            initially="DEFERRED",
        )

    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            alter table execution
            alter constraint execution_job_id_fkey deferrable initially deferred;
            """
        )
    # ### end Alembic commands ###
